# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/20230912tidytuesday',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/20230912tidytuesday',
                'lib_path': '20230912tidytuesday'},
  'syms': {'20230912tidytuesday.core': {'20230912tidytuesday.core.foo': ('core.html#foo', '20230912tidytuesday/core.py')}}}
